[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bfcl"
version = "0.1.0"
description = "Berkeley Function Calling Leaderboard (BFCL)"
authors = [
    {name="Shishir Patil", email="sgp@berkeley.edu"}
]
readme = "README.md"
requires-python = ">=3.9"
license = { "text" = "Apache 2.0" }
dependencies = [
    "requests",
    "tqdm",
    "numpy",
    "pandas",
    "huggingface_hub",
    "pydantic>=2.8.2",
    "python-dotenv>=1.0.1",
    "tree-sitter~=0.21.0",
    "tree-sitter-java==0.21.0",
    "tree-sitter-javascript==0.21.4",
    "openai>=1.35.10",
]

[tool.setuptools.packages.find]
include = ["bfcl*"]

[project.scripts]
bfcl = "bfcl.cli:main"

[project.urls]
Repository = "https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard"

[project.optional-dependencies]
oss_eval = ["vllm==0.5.1"]
proprietary_eval = [
    "mistralai==0.4.2",
    "anthropic==0.29.0",
    "cohere==5.2.5",
]
all = [
    "bfcl[oss_eval]",
    "bfcl[proprietary_eval]",
]