[tool.poetry]
name = "bfcl"
version = "0.1.0"
description = "Berkeley Function Calling Leaderboard (BFCL)"
authors = ["NAME <EMAIL>"]
readme = "README.md"
repository = "https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
requests = "*"
tqdm = "*"
numpy = "*"
shortuuid = "*"
huggingface_hub = "*"
pydantic = "^2.8.2"
python-dotenv = "^1.0.1"
tree-sitter = "^0.21.0"
datasets = "^2.19.2"
openai = "^1.35.10"
tree-sitter-java = "0.21.0"
tree-sitter-javascript = "0.21.4"
vllm = { version = "0.5.1", optional = true }
mistralai = { version = "^0.4.2", optional = true }
anthropic = { version = "^0.29.0", optional = true }
cohere = { version = "^5.2.5", optional = true }

[tool.poetry.extras]
oss_eval = ["vllm"]
proprietary_eval = [
    "mistralai",
    "anthropic",
    "cohere"
]

[tool.poetry.scripts]
bfcl_benchmark = "bfcl.benchmark:main"
bfcl_eval = "bfcl.evaluate:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
