name: Update API Zoo Data

on:
  push:
    branches:
      - main
    paths:
      - 'data/apizoo/**'

jobs:
  send-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Install Dependencies
        run: sudo apt-get install -y jq curl
      
      - name: Send Updated API Data to Server
        run: |
          REPO_URL="https://github.com/ShishirPatil/gorilla/blob/main/"
          FILES=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep 'data/apizoo/')
          for FILE in $FILES; do
            DATA=$(jq -c . < "$FILE")
            FILE_URL="${REPO_URL}${FILE}"
            JSON_BODY=$(jq --arg file_url "$FILE_URL" 'if type == "array" then map(. + {"file_url": $file_url}) else . + {"file_url": $file_url} end' <<< "$DATA")
            curl -X POST -H "Content-Type: application/json" -d "$JSON_BODY" http://34.123.98.138/api/update
          done
